bind = $mainMod SHIFT, F, fullscreenstate, -1 2

bind = CTRL ALT, T, exec, $terminal
bind = ALT, TAB, exec, rofi -show window -theme ~/.config/rofi/window.rasi
bind = , XF86Calculator, exec, gnome-calculator
bind = $mainMod, T, exec, $HOME/.config/hypr/scripts/theme-switcher.sh
binde =, XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
binde =, XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind =, XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

## Shell keybinds
# Launcher
bind = $mainMod, space, global, caelestia:launcher
bindin = $mainMod, mouse:272, global, caelestia:launcherInterrupt
bindin = $mainMod, mouse:273, global, caelestia:launcherInterrupt
bindin = $mainMod, mouse:274, global, caelestia:launcherInterrupt
bindin = $mainMod, mouse:275, global, caelestia:launcherInterrupt
bindin = $mainMod, mouse:276, global, caelestia:launcherInterrupt
bindin = $mainMod, mouse:277, global, caelestia:launcherInterrupt
bindin = $mainMod, mouse_up, global, caelestia:launcherInterrupt
bindin = $mainMod, mouse_down, global, caelestia:launcherInterrupt

# Utilities
bindl = , Print, global, caelestia:screenshotFreeze  # Capture region (freeze)
bindl = CTRL, Print, exec, caelestia screenshot  # Full screen capture > clipboard 

# Lock
bind = $mainMod SHIFT, L, global, caelestia:lock

#bind = Super+Alt, R, exec, caelestia record -s  # Record screen with sound
#bind = Ctrl+Alt, R, exec, caelestia record  # Record screen
#bind = Super+Shift+Alt, R, exec, caelestia record -r  # Record region
#bind = Super+Shift, C, exec, hyprpicker -a  # Colour picker
