windowrule {
  name = floating-window
  match:class = (Imprimer l'image|Cider|org.gnome.Calculator|org.gnome.Loupe)

  float = true
}

windowrule {
  name = kitty-term
  match:class = kitty

  size = (monitor_w*0.50) (monitor_h*0.47)
  float = true
  center = true
}

windowrule {
  name = floating-messages
  match:class = (signal|org.telegram.desktop)

  size = (monitor_w*0.27) (monitor_h*0.7)
  move = (monitor_w*0.70) (monitor_h*0.15)
  float = true
  pin = true
}

windowrule {
  name = filesystems
  match:class = DevTools|Tous les fichiers|org.gnome.Nautilus

  float = true
  center = true
  size = (monitor_w*0.48) (monitor_h*0.5)
}

windowrule {
  name = reaper
  match:class = REAPER

  move = cursor 
  float = true
}

windowrule {
  name = reaper-title
  match:class = REAPER
  match:title = ^(menu)$

  no_initial_focus = true
}

windowrule {
  name = pip
  match:class = zen
  match:title = Picture-in-Picture

  center = true
  size = 1280 720
  float = true
  pin = true
}

# exec-once = ~/.config/hypr/scripts/resize-window.sh
