windowrulev2 = float,class:(org.gnome.Nautilus|org.gnome.Calculator|org.gnome.Loupe)
windowrulev2 = size 35% 50%,class:(org.gnome.Nautilus)

windowrulev2 = float,class:(org.telegram.desktop|signal)
windowrulev2 = pin,class:(org.telegram.desktop|signal)
windowrulev2 = size 15% 70%,class:(org.telegram.desktop|signal)
windowrulev2 = move 83% 15%,class:(org.telegram.desktop|signal)

windowrulev2 = float, class:zen, title:(Picture-in-Picture)
windowrulev2 = pin, class:zen, title:(Picture-in-Picture)

windowrulev2 = float,title:(DevTools|Tous les fichiers|Imprimer l’image)
windowrulev2 = size 35% 50%,title:(DevTools|Tous les fichiers)

windowrulev2 = float,class:(kitty)
windowrulev2 = size 30% 40%,class:(kitty)

windowrulev2 = float,class:(Cider)
windowrulev2 = size 17% 62%,class:(Cider)

# REAPER
#windowrulev2 = tile,class:(REAPER)
windowrulev2 = move cursor,class:REAPER,floating:1
windowrulev2 = nofocus,class:REAPER,title:^(menu)$
windowrulev2 = nofocus,class:REAPER,title:^$

exec-once = ~/.config/hypr/scripts/resize-window.sh
