
# #######################################################################################
# MY SUPER HYPRLAND CONFIG.
# #######################################################################################

# Refer to the wiki for more information.
# https://wiki.hypr.land/Configuring/

################
### MONITORS ###
################

source = ~/.config/hypr/conf.d/monitors.conf

###################
### MY PROGRAMS ###
###################

source = ~/.config/hypr/conf.d/programs.conf

#################
### AUTOSTART ###
#################

source = ~/.config/hypr/conf.d/autostart.conf

#############################
### ENVIRONMENT VARIABLES ###
#############################

source = ~/.config/hypr/conf.d/environments.conf

###################
### PERMISSIONS ###
###################

source = ~/.config/hypr/conf.d/permissions.conf

#####################
### LOOK AND FEEL ###
#####################

source = ~/.config/hypr/conf.d/look-and-feel.conf

#############
### INPUT ###
#############

source = ~/.config/hypr/conf.d/inputs.conf

###################
### KEYBINDINGS ###
###################

source = ~/.config/hypr/conf.d/keybinds.conf

##############################
### WINDOWS AND WORKSPACES ###
##############################

source = ~/.config/hypr/conf.d/windowrules.conf

######################
### NOCTALIA THEME ###
######################

source = ~/.config/hypr/noctalia/noctalia-colors.conf

